import { MethodsResponseSchema } from './schema.js';
import { HyperFormula } from 'hyperformula';

// Function categories mapping based on function prefixes and known patterns
const FUNCTION_CATEGORIES = {
    // Math & Trigonometry
    ABS: 'Math & Trigonometry',
    ACOS: 'Math & Trigonometry',
    ACOSH: 'Math & Trigonometry',
    ACOT: 'Math & Trigonometry',
    ACOTH: 'Math & Trigonometry',
    ASIN: 'Math & Trigonometry',
    ASINH: 'Math & Trigonometry',
    ATAN: 'Math & Trigonometry',
    ATAN2: 'Math & Trigonometry',
    ATANH: 'Math & Trigonometry',
    COS: 'Math & Trigonometry',
    COSH: 'Math & Trigonometry',
    COT: 'Math & Trigonometry',
    COTH: 'Math & Trigonometry',
    CSC: 'Math & Trigonometry',
    CSCH: 'Math & Trigonometry',
    DEGREES: 'Math & Trigonometry',
    EXP: 'Math & Trigonometry',
    LN: 'Math & Trigonometry',
    LOG: 'Math & Trigonometry',
    LOG10: 'Math & Trigonometry',
    PI: 'Math & Trigonometry',
    POWER: 'Math & Trigonometry',
    RADIANS: 'Math & Trigonometry',
    SEC: 'Math & Trigonometry',
    SECH: 'Math & Trigonometry',
    SIN: 'Math & Trigonometry',
    SINH: 'Math & Trigonometry',
    SQRT: 'Math & Trigonometry',
    SQRTPI: 'Math & Trigonometry',
    TAN: 'Math & Trigonometry',
    TANH: 'Math & Trigonometry',
    TRUNC: 'Math & Trigonometry',
    ROUND: 'Math & Trigonometry',
    ROUNDDOWN: 'Math & Trigonometry',
    ROUNDUP: 'Math & Trigonometry',
    MROUND: 'Math & Trigonometry',
    CEILING: 'Math & Trigonometry',
    CEILINGMATH: 'Math & Trigonometry',
    CEILINGPRECISE: 'Math & Trigonometry',
    FLOOR: 'Math & Trigonometry',
    FLOORMATH: 'Math & Trigonometry',
    FLOORPRECISE: 'Math & Trigonometry',
    INT: 'Math & Trigonometry',
    MOD: 'Math & Trigonometry',
    PRODUCT: 'Math & Trigonometry',
    QUOTIENT: 'Math & Trigonometry',
    SIGN: 'Math & Trigonometry',
    GCD: 'Math & Trigonometry',
    LCM: 'Math & Trigonometry',
    COMBIN: 'Math & Trigonometry',
    COMBINA: 'Math & Trigonometry',
    FACT: 'Math & Trigonometry',
    FACTDOUBLE: 'Math & Trigonometry',
    MULTINOMIAL: 'Math & Trigonometry',
    RAND: 'Math & Trigonometry',
    RANDBETWEEN: 'Math & Trigonometry',
    ROMAN: 'Math & Trigonometry',
    ARABIC: 'Math & Trigonometry',
    SERIESSUM: 'Math & Trigonometry',
    SUMSQ: 'Math & Trigonometry',
    SUMX2MY2: 'Math & Trigonometry',
    SUMX2PY2: 'Math & Trigonometry',
    SUMXMY2: 'Math & Trigonometry',

    // Statistical
    AVEDEV: 'Statistical',
    AVERAGE: 'Statistical',
    AVERAGEA: 'Statistical',
    AVERAGEIF: 'Statistical',
    AVERAGEIFS: 'Statistical',
    COUNT: 'Statistical',
    COUNTA: 'Statistical',
    COUNTBLANK: 'Statistical',
    COUNTIF: 'Statistical',
    COUNTIFS: 'Statistical',
    MAX: 'Statistical',
    MAXA: 'Statistical',
    MIN: 'Statistical',
    MINA: 'Statistical',
    MEDIAN: 'Statistical',
    MODE: 'Statistical',
    MODEALL: 'Statistical',
    MODESNGL: 'Statistical',
    GEOMEAN: 'Statistical',
    HARMEAN: 'Statistical',
    TRIMMEAN: 'Statistical',
    CONFIDENCE: 'Statistical',
    STDEV: 'Statistical',
    STDEVA: 'Statistical',
    STDEVP: 'Statistical',
    STDEVPA: 'Statistical',
    STDEVS: 'Statistical',
    STDEVSA: 'Statistical',
    VAR: 'Statistical',
    VARA: 'Statistical',
    VARP: 'Statistical',
    VARPA: 'Statistical',
    VARS: 'Statistical',
    VARSA: 'Statistical',
    COVAR: 'Statistical',
    COVARIANCEP: 'Statistical',
    COVARIANCES: 'Statistical',
    CORREL: 'Statistical',
    PEARSON: 'Statistical',
    RSQ: 'Statistical',
    SKEW: 'Statistical',
    KURT: 'Statistical',
    SLOPE: 'Statistical',
    INTERCEPT: 'Statistical',
    FORECAST: 'Statistical',
    TREND: 'Statistical',
    GROWTH: 'Statistical',
    LINEST: 'Statistical',
    LOGEST: 'Statistical',
    STEYX: 'Statistical',
    PROB: 'Statistical',
    PERCENTILE: 'Statistical',
    PERCENTILEEXC: 'Statistical',
    PERCENTILEINC: 'Statistical',
    QUARTILE: 'Statistical',
    QUARTILEEXC: 'Statistical',
    QUARTILEINC: 'Statistical',
    PERCENTRANK: 'Statistical',
    PERCENTRANKEXC: 'Statistical',
    PERCENTRANKINC: 'Statistical',
    RANK: 'Statistical',
    RANKAVG: 'Statistical',
    RANKEQ: 'Statistical',
    LARGE: 'Statistical',
    SMALL: 'Statistical',
    FREQUENCY: 'Statistical',
    GAMMALN: 'Statistical',
    GAMMALNPRECISE: 'Statistical',
    BETA: 'Statistical',
    BETADIST: 'Statistical',
    BETAINV: 'Statistical',
    BINOMDIST: 'Statistical',
    BINOMDISTRANGE: 'Statistical',
    BINOMINV: 'Statistical',
    CHIDIST: 'Statistical',
    CHIINV: 'Statistical',
    CHITEST: 'Statistical',
    CRITBINOM: 'Statistical',
    EXPONDIST: 'Statistical',
    FDIST: 'Statistical',
    FINV: 'Statistical',
    FTEST: 'Statistical',
    GAMMADIST: 'Statistical',
    GAMMAINV: 'Statistical',
    HYPGEOMDIST: 'Statistical',
    LOGNORMDIST: 'Statistical',
    LOGINV: 'Statistical',
    NEGBINOMDIST: 'Statistical',
    NORMDIST: 'Statistical',
    NORMINV: 'Statistical',
    NORMSDIST: 'Statistical',
    NORMSINV: 'Statistical',
    POISSONDIST: 'Statistical',
    STDIST: 'Statistical',
    TINV: 'Statistical',
    TTEST: 'Statistical',
    WEIBULLDIST: 'Statistical',
    ZTEST: 'Statistical',
    PHI: 'Statistical',

    // Logical
    AND: 'Logical',
    FALSE: 'Logical',
    IF: 'Logical',
    IFERROR: 'Logical',
    IFNA: 'Logical',
    NOT: 'Logical',
    OR: 'Logical',
    TRUE: 'Logical',
    XOR: 'Logical',
    SWITCH: 'Logical',

    // Text
    CHAR: 'Text',
    CLEAN: 'Text',
    CODE: 'Text',
    CONCATENATE: 'Text',
    CONCAT: 'Text',
    EXACT: 'Text',
    FIND: 'Text',
    FINDB: 'Text',
    FIXED: 'Text',
    LEFT: 'Text',
    LEFTB: 'Text',
    LEN: 'Text',
    LENB: 'Text',
    LOWER: 'Text',
    MID: 'Text',
    MIDB: 'Text',
    NUMBERVALUE: 'Text',
    PHONETIC: 'Text',
    PROPER: 'Text',
    REPLACE: 'Text',
    REPLACEB: 'Text',
    REPT: 'Text',
    RIGHT: 'Text',
    RIGHTB: 'Text',
    SEARCH: 'Text',
    SEARCHB: 'Text',
    SUBSTITUTE: 'Text',
    T: 'Text',
    TEXT: 'Text',
    TEXTJOIN: 'Text',
    TRIM: 'Text',
    UNICHAR: 'Text',
    UNICODE: 'Text',
    UPPER: 'Text',
    VALUE: 'Text',

    // Lookup & Reference
    ADDRESS: 'Lookup & Reference',
    AREAS: 'Lookup & Reference',
    CHOOSE: 'Lookup & Reference',
    CHOOSECOLS: 'Lookup & Reference',
    CHOOSEROWS: 'Lookup & Reference',
    COLUMN: 'Lookup & Reference',
    COLUMNS: 'Lookup & Reference',
    DROP: 'Lookup & Reference',
    EXPAND: 'Lookup & Reference',
    FILTER: 'Lookup & Reference',
    FORMULATEXT: 'Lookup & Reference',
    GETPIVOTDATA: 'Lookup & Reference',
    HLOOKUP: 'Lookup & Reference',
    HSTACK: 'Lookup & Reference',
    INDEX: 'Lookup & Reference',
    INDIRECT: 'Lookup & Reference',
    LOOKUP: 'Lookup & Reference',
    MATCH: 'Lookup & Reference',
    OFFSET: 'Lookup & Reference',
    ROW: 'Lookup & Reference',
    ROWS: 'Lookup & Reference',
    SHEET: 'Lookup & Reference',
    SHEETS: 'Lookup & Reference',
    SORT: 'Lookup & Reference',
    SORTBY: 'Lookup & Reference',
    TAKE: 'Lookup & Reference',
    TOCOL: 'Lookup & Reference',
    TOROW: 'Lookup & Reference',
    TRANSPOSE: 'Lookup & Reference',
    UNIQUE: 'Lookup & Reference',
    VLOOKUP: 'Lookup & Reference',
    VSTACK: 'Lookup & Reference',
    WRAPCOLS: 'Lookup & Reference',
    WRAPROWS: 'Lookup & Reference',
    XLOOKUP: 'Lookup & Reference',
    XMATCH: 'Lookup & Reference',

    // Date & Time
    DATE: 'Date & Time',
    DATEDIF: 'Date & Time',
    DATEVALUE: 'Date & Time',
    DAY: 'Date & Time',
    DAYS: 'Date & Time',
    DAYS360: 'Date & Time',
    EDATE: 'Date & Time',
    EOMONTH: 'Date & Time',
    HOUR: 'Date & Time',
    ISOWEEKNUM: 'Date & Time',
    MINUTE: 'Date & Time',
    MONTH: 'Date & Time',
    NETWORKDAYS: 'Date & Time',
    NETWORKDAYSINTL: 'Date & Time',
    NOW: 'Date & Time',
    SECOND: 'Date & Time',
    TIME: 'Date & Time',
    TIMEVALUE: 'Date & Time',
    TODAY: 'Date & Time',
    WEEKDAY: 'Date & Time',
    WEEKNUM: 'Date & Time',
    WORKDAY: 'Date & Time',
    WORKDAYINTL: 'Date & Time',
    YEAR: 'Date & Time',
    YEARFRAC: 'Date & Time',

    // Financial
    ACCRINT: 'Financial',
    ACCRINTM: 'Financial',
    AMORDEGRC: 'Financial',
    AMORLINC: 'Financial',
    COUPDAYBS: 'Financial',
    COUPDAYS: 'Financial',
    COUPDAYSNC: 'Financial',
    COUPNCD: 'Financial',
    COUPNUM: 'Financial',
    COUPPCD: 'Financial',
    CUMIPMT: 'Financial',
    CUMPRINC: 'Financial',
    DB: 'Financial',
    DDB: 'Financial',
    DISC: 'Financial',
    DOLLARDE: 'Financial',
    DOLLARFR: 'Financial',
    DURATION: 'Financial',
    EFFECT: 'Financial',
    FV: 'Financial',
    FVSCHEDULE: 'Financial',
    INTRATE: 'Financial',
    IPMT: 'Financial',
    IRR: 'Financial',
    ISPMT: 'Financial',
    MDURATION: 'Financial',
    MIRR: 'Financial',
    NOMINAL: 'Financial',
    NPER: 'Financial',
    NPV: 'Financial',
    ODDFPRICE: 'Financial',
    ODDFYIELD: 'Financial',
    ODDLPRICE: 'Financial',
    ODDLYIELD: 'Financial',
    PDURATION: 'Financial',
    PMT: 'Financial',
    PPMT: 'Financial',
    PRICE: 'Financial',
    PRICEDISC: 'Financial',
    PRICEMAT: 'Financial',
    PV: 'Financial',
    RATE: 'Financial',
    RECEIVED: 'Financial',
    RRI: 'Financial',
    SLN: 'Financial',
    SYD: 'Financial',
    TBILLEQ: 'Financial',
    TBILLPRICE: 'Financial',
    TBILLYIELD: 'Financial',
    VDB: 'Financial',
    XIRR: 'Financial',
    XNPV: 'Financial',
    YIELD: 'Financial',
    YIELDDISC: 'Financial',
    YIELDMAT: 'Financial',

    // Engineering
    BESSELI: 'Engineering',
    BESSELJ: 'Engineering',
    BESSELK: 'Engineering',
    BESSELY: 'Engineering',
    BIN2DEC: 'Engineering',
    BIN2HEX: 'Engineering',
    BIN2OCT: 'Engineering',
    BITAND: 'Engineering',
    BITLSHIFT: 'Engineering',
    BITOR: 'Engineering',
    BITRSHIFT: 'Engineering',
    BITXOR: 'Engineering',
    COMPLEX: 'Engineering',
    CONVERT: 'Engineering',
    DEC2BIN: 'Engineering',
    DEC2HEX: 'Engineering',
    DEC2OCT: 'Engineering',
    DELTA: 'Engineering',
    ERF: 'Engineering',
    ERFC: 'Engineering',
    ERFPRECISE: 'Engineering',
    GESTEP: 'Engineering',
    HEX2BIN: 'Engineering',
    HEX2DEC: 'Engineering',
    HEX2OCT: 'Engineering',
    IMABS: 'Engineering',
    IMAGINARY: 'Engineering',
    IMARGUMENT: 'Engineering',
    IMCONJUGATE: 'Engineering',
    IMCOS: 'Engineering',
    IMCOSH: 'Engineering',
    IMCOT: 'Engineering',
    IMCSC: 'Engineering',
    IMCSCH: 'Engineering',
    IMDIV: 'Engineering',
    IMEXP: 'Engineering',
    IMLN: 'Engineering',
    IMLOG10: 'Engineering',
    IMLOG2: 'Engineering',
    IMPOWER: 'Engineering',
    IMPRODUCT: 'Engineering',
    IMREAL: 'Engineering',
    IMSEC: 'Engineering',
    IMSECH: 'Engineering',
    IMSIN: 'Engineering',
    IMSINH: 'Engineering',
    IMSQRT: 'Engineering',
    IMSUB: 'Engineering',
    IMSUM: 'Engineering',
    IMTAN: 'Engineering',
    IMTANH: 'Engineering',
    OCT2BIN: 'Engineering',
    OCT2DEC: 'Engineering',
    OCT2HEX: 'Engineering',

    // Information
    CELL: 'Information',
    ERROR: 'Information',
    INFO: 'Information',
    ISBLANK: 'Information',
    ISERR: 'Information',
    ISERROR: 'Information',
    ISEVEN: 'Information',
    ISFORMULA: 'Information',
    ISLOGICAL: 'Information',
    ISNA: 'Information',
    ISNONTEXT: 'Information',
    ISNUMBER: 'Information',
    ISODD: 'Information',
    ISREF: 'Information',
    ISTEXT: 'Information',
    N: 'Information',
    NA: 'Information',
    SHEETNAME: 'Information',
    TYPE: 'Information',

    // Math
    SUM: 'Math',
    SUMIF: 'Math',
    SUMIFS: 'Math',
    SUMPRODUCT: 'Math',
    SUBTOTAL: 'Math',
    AGGREGATE: 'Math',
    BASE: 'Math',
    DECIMAL: 'Math',

    // Array
    ARRAYFORMULA: 'Array',
    MMULT: 'Array',
    MDETERM: 'Array',
    MINVERSE: 'Array',
    MUNIT: 'Array',

    // Database
    DAVERAGE: 'Database',
    DCOUNT: 'Database',
    DCOUNTA: 'Database',
    DGET: 'Database',
    DMAX: 'Database',
    DMIN: 'Database',
    DPRODUCT: 'Database',
    DSTDEV: 'Database',
    DSTDEVP: 'Database',
    DSUM: 'Database',
    DVAR: 'Database',
    DVARP: 'Database',

    // Web
    ENCODEURL: 'Web',
    WEBSERVICE: 'Web',

    // Version
    VERSION: 'Version'
};

// Example formulas for common functions
const EXAMPLE_FORMULAS = {
    // Logical
    IF: ['=IF(A1>10, "High", "Low")', '=IF(B2="Yes", 100, 0)'],
    AND: ['=AND(A1>0, A1<10)', '=AND(B1="Yes", C1>0)'],
    OR: ['=OR(A1=1, A1=2)', '=OR(B1="Red", B1="Blue")'],
    NOT: ['=NOT(A1>5)', '=NOT(B1="Complete")'],
    TRUE: ['=TRUE()', '=IF(A1>0, TRUE, FALSE)'],
    FALSE: ['=FALSE()', '=IF(A1<0, TRUE, FALSE)'],
    IFERROR: ['=IFERROR(A1/B1, 0)', '=IFERROR(VLOOKUP(A1, B:C, 2, FALSE), "Not Found")'],
    IFNA: ['=IFNA(VLOOKUP(A1, B:C, 2, FALSE), "No Match")'],
    XOR: ['=XOR(A1>0, B1>0)', '=XOR(TRUE, FALSE)'],
    SWITCH: ['=SWITCH(A1, 1, "One", 2, "Two", "Other")'],

    // Math
    SUM: ['=SUM(A1:A10)', '=SUM(A1, B1, C1)'],
    SUMIF: ['=SUMIF(A1:A10, ">5")', '=SUMIF(A1:A10, "Apples", B1:B10)'],
    SUMIFS: ['=SUMIFS(B1:B10, A1:A10, ">5")', '=SUMIFS(C1:C10, A1:A10, "East", B1:B10, ">100")'],
    SUMPRODUCT: ['=SUMPRODUCT(A1:A10, B1:B10)', '=SUMPRODUCT((A1:A10>5)*(B1:B10))'],
    PRODUCT: ['=PRODUCT(A1:A5)', '=PRODUCT(A1, B1, C1)'],
    SUBTOTAL: ['=SUBTOTAL(9, A1:A10)', '=SUBTOTAL(109, A1:A10)'],
    AGGREGATE: ['=AGGREGATE(9, 3, A1:A10)', '=AGGREGATE(2, 5, A1:A10)'],
    POWER: ['=POWER(2, 3)', '=POWER(A1, 2)'],
    SQRT: ['=SQRT(16)', '=SQRT(A1)'],
    ABS: ['=ABS(-10)', '=ABS(A1-B1)'],
    ROUND: ['=ROUND(3.14159, 2)', '=ROUND(A1, 0)'],
    ROUNDDOWN: ['=ROUNDDOWN(3.9, 0)', '=ROUNDDOWN(A1, 2)'],
    ROUNDUP: ['=ROUNDUP(3.1, 0)', '=ROUNDUP(A1, 2)'],
    MROUND: ['=MROUND(17, 5)', '=MROUND(A1, 10)'],
    CEILING: ['=CEILING(3.2, 1)', '=CEILING(A1, 10)'],
    CEILINGMATH: ['=CEILINGMATH(3.2)', '=CEILINGMATH(A1, 10)'],
    FLOOR: ['=FLOOR(3.9, 1)', '=FLOOR(A1, 10)'],
    FLOORMATH: ['=FLOORMATH(3.9)', '=FLOORMATH(A1, 10)'],
    INT: ['=INT(3.9)', '=INT(-3.9)'],
    TRUNC: ['=TRUNC(3.9)', '=TRUNC(3.14159, 2)'],
    MOD: ['=MOD(17, 5)', '=MOD(A1, B1)'],
    QUOTIENT: ['=QUOTIENT(17, 5)', '=QUOTIENT(A1, B1)'],
    SIGN: ['=SIGN(-10)', '=SIGN(A1)'],
    GCD: ['=GCD(24, 36)', '=GCD(A1, B1, C1)'],
    LCM: ['=LCM(4, 6)', '=LCM(A1, B1)'],
    COMBIN: ['=COMBIN(10, 3)', '=COMBIN(A1, B1)'],
    FACT: ['=FACT(5)', '=FACT(A1)'],
    RAND: ['=RAND()', '=RAND()*100'],
    RANDBETWEEN: ['=RANDBETWEEN(1, 100)', '=RANDBETWEEN(A1, B1)'],

    // Statistical
    AVERAGE: ['=AVERAGE(A1:A10)', '=AVERAGE(A1, B1, C1)'],
    AVERAGEA: ['=AVERAGEA(A1:A10)', '=AVERAGEA(A1, "5", TRUE)'],
    AVERAGEIF: ['=AVERAGEIF(A1:A10, ">5")', '=AVERAGEIF(A1:A10, "*apple*", B1:B10)'],
    AVERAGEIFS: ['=AVERAGEIFS(B1:B10, A1:A10, ">5")'],
    COUNT: ['=COUNT(A1:A10)', '=COUNT(A1, B1, C1)'],
    COUNTA: ['=COUNTA(A1:A10)', '=COUNTA(A1:B10)'],
    COUNTBLANK: ['=COUNTBLANK(A1:A10)', '=COUNTBLANK(A1:C10)'],
    COUNTIF: ['=COUNTIF(A1:A10, ">5")', '=COUNTIF(A1:A10, "Apples")'],
    COUNTIFS: ['=COUNTIFS(A1:A10, ">5", B1:B10, "Yes")'],
    MAX: ['=MAX(A1:A10)', '=MAX(A1, B1, C1)'],
    MAXA: ['=MAXA(A1:A10)', '=MAXA(A1, B1, "10")'],
    MIN: ['=MIN(A1:A10)', '=MIN(A1, B1, C1)'],
    MINA: ['=MINA(A1:A10)', '=MINA(A1, B1, "10")'],
    MEDIAN: ['=MEDIAN(A1:A10)', '=MEDIAN(1, 2, 3, 4, 5)'],
    MODE: ['=MODE(A1:A10)', '=MODE(1, 2, 2, 3, 3, 3)'],
    STDEV: ['=STDEV(A1:A10)', '=STDEV(A1, B1, C1)'],
    STDEVP: ['=STDEVP(A1:A10)', '=STDEVP(A1, B1, C1)'],
    VAR: ['=VAR(A1:A10)', '=VAR(A1, B1, C1)'],
    VARP: ['=VARP(A1:A10)', '=VARP(A1, B1, C1)'],
    CORREL: ['=CORREL(A1:A10, B1:B10)'],
    PEARSON: ['=PEARSON(A1:A10, B1:B10)'],
    PERCENTILE: ['=PERCENTILE(A1:A10, 0.5)', '=PERCENTILE(A1:A10, 0.9)'],
    QUARTILE: ['=QUARTILE(A1:A10, 1)', '=QUARTILE(A1:A10, 3)'],
    RANK: ['=RANK(A1, A1:A10, 0)', '=RANK(B1, B1:B10, 1)'],
    LARGE: ['=LARGE(A1:A10, 1)', '=LARGE(A1:A10, 3)'],
    SMALL: ['=SMALL(A1:A10, 1)', '=SMALL(A1:A10, 3)'],

    // Lookup & Reference
    VLOOKUP: ['=VLOOKUP(A1, B1:D10, 2, FALSE)', '=VLOOKUP("Apple", A1:B10, 2, TRUE)'],
    HLOOKUP: ['=HLOOKUP(A1, A1:F5, 3, FALSE)', '=HLOOKUP("Total", A1:F5, 2, TRUE)'],
    INDEX: ['=INDEX(A1:C10, 5, 2)', '=INDEX(A1:C10, MATCH(A15, A1:A10, 0), 2)'],
    MATCH: ['=MATCH(A1, A1:A10, 0)', '=MATCH("Apple", A1:A10, 0)'],
    XLOOKUP: ['=XLOOKUP(A1, B1:B10, C1:C10)', '=XLOOKUP("John", A1:A10, B1:D10, "Not Found")'],
    XMATCH: ['=XMATCH(A1, A1:A10, 0)', '=XMATCH("Apple", A1:A10, -1)'],
    CHOOSE: ['=CHOOSE(A1, "First", "Second", "Third")', '=CHOOSE(2, A1, B1, C1)'],
    LOOKUP: ['=LOOKUP(A1, A1:A10, B1:B10)', '=LOOKUP("Apple", A1:A10)'],
    OFFSET: ['=OFFSET(A1, 2, 1)', '=OFFSET(A1, B1, C1, 3, 2)'],
    INDIRECT: ['=INDIRECT("A1")', '=INDIRECT("Sheet" & A1 & "!B" & B1)'],
    ADDRESS: ['=ADDRESS(5, 2)', '=ADDRESS(A1, B1, 4)'],
    ROW: ['=ROW()', '=ROW(A1)'],
    ROWS: ['=ROWS(A1:C10)', '=ROWS(A1:A10)'],
    COLUMN: ['=COLUMN()', '=COLUMN(B1)'],
    COLUMNS: ['=COLUMNS(A1:C10)', '=COLUMNS(A1:A10)'],
    TRANSPOSE: ['=TRANSPOSE(A1:C3)', '=TRANSPOSE(A1:A10)'],
    SORT: ['=SORT(A1:C10)', '=SORT(A1:C10, 2, -1)'],
    UNIQUE: ['=UNIQUE(A1:A10)', '=UNIQUE(A1:B10, TRUE)'],
    FILTER: ['=FILTER(A1:C10, B1:B10>5)', '=FILTER(A1:C10, (B1:B10>5)*(C1:C10<100))'],

    // Date & Time
    DATE: ['=DATE(2024, 3, 15)', '=DATE(A1, B1, C1)'],
    TODAY: ['=TODAY()', '=TODAY()+7'],
    NOW: ['=NOW()', '=NOW()-1'],
    DAY: ['=DAY(A1)', '=DAY(DATE(2024, 3, 15))'],
    MONTH: ['=MONTH(A1)', '=MONTH(DATE(2024, 3, 15))'],
    YEAR: ['=YEAR(A1)', '=YEAR(DATE(2024, 3, 15))'],
    HOUR: ['=HOUR(A1)', '=HOUR(NOW())'],
    MINUTE: ['=HOUR(A1)', '=MINUTE(NOW())'],
    SECOND: ['=SECOND(A1)', '=SECOND(NOW())'],
    TIME: ['=TIME(14, 30, 0)', '=TIME(A1, B1, C1)'],
    TIMEVALUE: ['=TIMEVALUE("14:30")', '=TIMEVALUE(A1)'],
    DATEVALUE: ['=DATEVALUE("2024-03-15")', '=DATEVALUE(A1)'],
    DAYS: ['=DAYS(A1, B1)', '=DAYS(TODAY(), DATE(2024, 1, 1))'],
    DAYS360: ['=DAYS360(A1, B1)', '=DAYS360(DATE(2024, 1, 1), DATE(2024, 12, 31))'],
    EDATE: ['=EDATE(TODAY(), 3)', '=EDATE(A1, 6)'],
    EOMONTH: ['=EOMONTH(TODAY(), 0)', '=EOMONTH(A1, -1)'],
    NETWORKDAYS: ['=NETWORKDAYS(A1, B1)', '=NETWORKDAYS(A1, B1, C1:C5)'],
    NETWORKDAYSINTL: ['=NETWORKDAYSINTL(A1, B1, 7)', '=NETWORKDAYSINTL(A1, B1, "0000011")'],
    WORKDAY: ['=WORKDAY(TODAY(), 10)', '=WORKDAY(A1, 5, B1:B3)'],
    WORKDAYINTL: ['=WORKDAYINTL(TODAY(), 10, 7)', '=WORKDAYINTL(A1, 5, "0000011")'],
    WEEKNUM: ['=WEEKNUM(A1)', '=WEEKNUM(A1, 2)'],
    ISOWEEKNUM: ['=ISOWEEKNUM(A1)', '=ISOWEEKNUM(TODAY())'],
    WEEKDAY: ['=WEEKDAY(A1)', '=WEEKDAY(A1, 2)'],
    YEARFRAC: ['=YEARFRAC(A1, B1)', '=YEARFRAC(A1, B1, 1)'],
    DATEDIF: ['=DATEDIF(A1, B1, "Y")', '=DATEDIF(A1, B1, "M")'],

    // Text
    CONCATENATE: ['=CONCATENATE(A1, " ", B1)', '=CONCATENATE("Hello", " ", "World")'],
    CONCAT: ['=CONCAT(A1, B1, C1)', '=CONCAT(A1:C10)'],
    TEXTJOIN: ['=TEXTJOIN(", ", TRUE, A1:A10)', '=TEXTJOIN("-", FALSE, A1, B1, C1)'],
    LEFT: ['=LEFT(A1, 3)', '=LEFT(A1)'],
    RIGHT: ['=RIGHT(A1, 3)', '=RIGHT(A1)'],
    MID: ['=MID(A1, 2, 3)', '=MID(A1, B1, C1)'],
    LEN: ['=LEN(A1)', '=LEN("Hello World")'],
    TRIM: ['=TRIM(A1)', '=TRIM("  Hello  ")'],
    UPPER: ['=UPPER(A1)', '=UPPER("hello")'],
    LOWER: ['=LOWER(A1)', '=LOWER("HELLO")'],
    PROPER: ['=PROPER(A1)', '=PROPER("hello world")'],
    FIND: ['=FIND("a", A1)', '=FIND("the", A1, 10)'],
    SEARCH: ['=SEARCH("a", A1)', '=SEARCH("the", A1, 10)'],
    SUBSTITUTE: ['=SUBSTITUTE(A1, "old", "new")', '=SUBSTITUTE(A1, "a", "b", 2)'],
    REPLACE: ['=REPLACE(A1, 2, 3, "XYZ")', '=REPLACE(A1, B1, C1, "New")'],
    REPT: ['=REPT("*", 10)', '=REPT(A1, B1)'],
    TEXT: ['=TEXT(A1, "0.00")', '=TEXT(A1, "mmmm d, yyyy")'],
    VALUE: ['=VALUE(A1)', '=VALUE("123.45")'],
    EXACT: ['=EXACT(A1, B1)', '=EXACT("Hello", "hello")'],
    CHAR: ['=CHAR(65)', '=CHAR(A1)'],
    CODE: ['=CODE(A1)', '=CODE("A")'],
    UNICHAR: ['=UNICHAR(65)', '=UNICHAR(A1)'],
    UNICODE: ['=UNICODE(A1)', '=UNICODE("A")'],
    CLEAN: ['=CLEAN(A1)', '=CLEAN(CHAR(9)&"Hello"&CHAR(10))'],
    T: ['=T(A1)', '=T(123)'],

    // Financial
    FV: ['=FV(0.05/12, 360, -1000, 0, 0)', '=FV(A1/12, B1, -C1)'],
    PV: ['=PV(0.05/12, 360, -1000, 0, 0)', '=PV(A1/12, B1, -C1)'],
    PMT: ['=PMT(0.05/12, 360, 200000)', '=PMT(A1, B1, C1)'],
    PPMT: ['=PPMT(0.05/12, 1, 360, 200000)', '=PPMT(A1, B1, C1, D1)'],
    IPMT: ['=IPMT(0.05/12, 1, 360, 200000)', '=IPMT(A1, B1, C1, D1)'],
    NPER: ['=NPER(0.05/12, -1000, 200000)', '=NPER(A1, B1, C1)'],
    RATE: ['=RATE(360, -1000, 200000)', '=RATE(A1, B1, C1)'],
    NPV: ['=NPV(0.1, A1:A5)', '=NPV(A1, B1:B5) + C1'],
    IRR: ['=IRR(A1:A5)', '=IRR(A1:A5, 0.1)'],
    XIRR: ['=XIRR(A1:A5, B1:B5)', '=XIRR(A1:A5, B1:B5, 0.1)'],
    XNPV: ['=XNPV(0.1, A1:A5, B1:B5)'],
    EFFECT: ['=EFFECT(0.05, 12)', '=EFFECT(A1, B1)'],
    NOMINAL: ['=NOMINAL(0.0512, 12)', '=NOMINAL(A1, B1)'],
    DB: ['=DB(10000, 1000, 5, 1)', '=DB(A1, B1, C1, D1)'],
    DDB: ['=DDB(10000, 1000, 5, 1)', '=DDB(A1, B1, C1, D1, E1)'],
    SLN: ['=SLN(10000, 1000, 5)', '=SLN(A1, B1, C1)'],
    SYD: ['=SYD(10000, 1000, 5, 1)', '=SYD(A1, B1, C1, D1)'],
    CUMIPMT: ['=CUMIPMT(0.05/12, 360, 200000, 1, 12, 0)'],
    CUMPRINC: ['=CUMPRINC(0.05/12, 360, 200000, 1, 12, 0)'],
    RRI: ['=RRI(5, 1000, 1500)', '=RRI(A1, B1, C1)'],
    PDURATION: ['=PDURATION(0.05, 1000, 1500)', '=PDURATION(A1, B1, C1)'],
    FVSCHEDULE: ['=FVSCHEDULE(1000, A1:A5)'],

    // Engineering
    BIN2DEC: ['=BIN2DEC(101)', '=BIN2DEC(A1)'],
    BIN2HEX: ['=BIN2HEX(101)', '=BIN2HEX(A1, 4)'],
    BIN2OCT: ['=BIN2OCT(101)', '=BIN2OCT(A1, 4)'],
    DEC2BIN: ['=DEC2BIN(5)', '=DEC2BIN(A1, 8)'],
    DEC2HEX: ['=DEC2HEX(255)', '=DEC2HEX(A1, 4)'],
    DEC2OCT: ['=DEC2OCT(255)', '=DEC2OCT(A1, 4)'],
    HEX2BIN: ['=HEX2BIN("FF")', '=HEX2BIN(A1, 8)'],
    HEX2DEC: ['=HEX2DEC("FF")', '=HEX2DEC(A1)'],
    HEX2OCT: ['=HEX2OCT("FF")', '=HEX2OCT(A1, 4)'],
    OCT2BIN: ['=OCT2BIN("77")', '=OCT2BIN(A1, 8)'],
    OCT2DEC: ['=OCT2DEC("77")', '=OCT2DEC(A1)'],
    OCT2HEX: ['=OCT2HEX("77")', '=OCT2HEX(A1, 4)'],
    BITAND: ['=BITAND(5, 3)', '=BITAND(A1, B1)'],
    BITOR: ['=BITOR(5, 3)', '=BITOR(A1, B1)'],
    BITXOR: ['=BITXOR(5, 3)', '=BITXOR(A1, B1)'],
    BITLSHIFT: ['=BITLSHIFT(5, 2)', '=BITLSHIFT(A1, B1)'],
    BITRSHIFT: ['=BITRSHIFT(5, 1)', '=BITRSHIFT(A1, B1)'],
    DELTA: ['=DELTA(5, 5)', '=DELTA(A1, B1)'],
    GESTEP: ['=GESTEP(5, 3)', '=GESTEP(A1, B1)'],
    COMPLEX: ['=COMPLEX(3, 4)', '=COMPLEX(A1, B1, "j")'],
    CONVERT: ['=CONVERT(100, "m", "ft")', '=CONVERT(A1, "kg", "lbm")'],
    IMABS: ['=IMABS("3+4i")', '=IMABS(A1)'],
    IMAGINARY: ['=IMAGINARY("3+4i")', '=IMAGINARY(A1)'],
    IMREAL: ['=IMREAL("3+4i")', '=IMREAL(A1)'],
    IMARGUMENT: ['=IMARGUMENT("3+4i")', '=IMARGUMENT(A1)'],
    IMCONJUGATE: ['=IMCONJUGATE("3+4i")', '=IMCONJUGATE(A1)'],
    IMCOS: ['=IMCOS("3+4i")', '=IMCOS(A1)'],
    IMCOSH: ['=IMCOSH("3+4i")', '=IMCOSH(A1)'],
    IMCOT: ['=IMCOT("3+4i")', '=IMCOT(A1)'],
    IMCSC: ['=IMCSC("3+4i")', '=IMCSC(A1)'],
    IMSEC: ['=IMSEC("3+4i")', '=IMSEC(A1)'],
    IMSECH: ['=IMSECH("3+4i")', '=IMSECH(A1)'],
    IMSIN: ['=IMSIN("3+4i")', '=IMSIN(A1)'],
    IMSINH: ['=IMSINH("3+4i")', '=IMSINH(A1)'],
    IMTAN: ['=IMTAN("3+4i")', '=IMTAN(A1)'],
    IMTANH: ['=IMTANH("3+4i")', '=IMTANH(A1)'],
    IMLN: ['=IMLN("3+4i")', '=IMLN(A1)'],
    IMLOG10: ['=IMLOG10("3+4i")', '=IMLOG10(A1)'],
    IMLOG2: ['=IMLOG2("3+4i")', '=IMLOG2(A1)'],
    IMEXP: ['=IMEXP("3+4i")', '=IMEXP(A1)'],
    IMPOWER: ['=IMPOWER("3+4i", 2)', '=IMPOWER(A1, B1)'],
    IMPRODUCT: ['=IMPRODUCT("3+4i", "1+2i")', '=IMPRODUCT(A1, B1)'],
    IMSUM: ['=IMSUM("3+4i", "1+2i")', '=IMSUM(A1, B1)'],
    IMSUB: ['=IMSUB("3+4i", "1+2i")', '=IMSUB(A1, B1)'],
    IMSQRT: ['=IMSQRT("3+4i")', '=IMSQRT(A1)'],
    IMDIV: ['=IMDIV("3+4i", "1+2i")', '=IMDIV(A1, B1)'],
    ERF: ['=ERF(1)', '=ERF(A1)'],
    ERFC: ['=ERFC(1)', '=ERFC(A1)'],

    // Information
    ISBLANK: ['=ISBLANK(A1)', '=IF(ISBLANK(A1), "Empty", "Not Empty")'],
    ISERR: ['=ISERR(A1)', '=IF(ISERR(A1/B1), "Error", A1/B1)'],
    ISERROR: ['=ISERROR(A1)', '=IF(ISERROR(A1/B1), "Error", A1/B1)'],
    ISLOGICAL: ['=ISLOGICAL(A1)', '=ISLOGICAL(TRUE())'],
    ISNA: ['=ISNA(VLOOKUP(A1, B:C, 2, FALSE))'],
    ISNONTEXT: ['=ISNONTEXT(A1)', '=ISNONTEXT(123)'],
    ISNUMBER: ['=ISNUMBER(A1)', '=IF(ISNUMBER(A1), A1*2, 0)'],
    ISREF: ['=ISREF(A1)', '=ISREF(A1:B10)'],
    ISTEXT: ['=ISTEXT(A1)', '=IF(ISTEXT(A1), "Text", "Not Text")'],
    ISFORMULA: ['=ISFORMULA(A1)', '=IF(ISFORMULA(A1), "Formula", "Value")'],
    ISEVEN: ['=ISEVEN(A1)', '=ISEVEN(4)'],
    ISODD: ['=ISODD(A1)', '=ISODD(5)'],
    N: ['=N(A1)', '=N("123")'],
    NA: ['=NA()', '=IF(A1="", NA(), A1)'],
    TYPE: ['=TYPE(A1)', '=TYPE(123)', '=TYPE("Text")'],

    // Trigonometry
    SIN: ['=SIN(PI()/2)', '=SIN(A1)'],
    COS: ['=COS(PI())', '=COS(A1)'],
    TAN: ['=TAN(PI()/4)', '=TAN(A1)'],
    ASIN: ['=ASIN(0.5)', '=ASIN(A1)'],
    ACOS: ['=ACOS(0.5)', '=ACOS(A1)'],
    ATAN: ['=ATAN(1)', '=ATAN(A1)'],
    ATAN2: ['=ATAN2(1, 1)', '=ATAN2(A1, B1)'],
    SINH: ['=SINH(1)', '=SINH(A1)'],
    COSH: ['=COSH(1)', '=COSH(A1)'],
    TANH: ['=TANH(1)', '=TANH(A1)'],
    ASINH: ['=ASINH(1)', '=ASINH(A1)'],
    ACOSH: ['=ACOSH(2)', '=ACOSH(A1)'],
    ATANH: ['=ATANH(0.5)', '=ATANH(A1)'],
    COT: ['=COT(PI()/4)', '=COT(A1)'],
    ACOT: ['=ACOT(1)', '=ACOT(A1)'],
    COTH: ['=COTH(1)', '=COTH(A1)'],
    ACOTH: ['=ACOTH(2)', '=ACOTH(A1)'],
    SEC: ['=SEC(PI()/3)', '=SEC(A1)'],
    CSC: ['=CSC(PI()/6)', '=CSC(A1)'],
    SECH: ['=SECH(1)', '=SECH(A1)'],
    CSCH: ['=CSCH(1)', '=CSCH(A1)'],
    DEGREES: ['=DEGREES(PI())', '=DEGREES(A1)'],
    RADIANS: ['=RADIANS(180)', '=RADIANS(A1)'],
    PI: ['=PI()', '=2*PI()'],

    // Array functions
    ARRAYFORMULA: ['=ARRAYFORMULA(A1:C3 * 2)', '=ARRAYFORMULA(SUM(A1:A10 * B1:B10))'],
    MMULT: ['=MMULT(A1:B2, C1:D2)', '=MMULT(A1:C3, D1:F3)'],
    MDETERM: ['=MDETERM(A1:C3)', '=MDETERM(A1:B2)'],
    MINVERSE: ['=MINVERSE(A1:B2)', '=MINVERSE(A1:C3)'],
    MUNIT: ['=MUNIT(3)', '=MUNIT(A1)'],

    // Database functions
    DSUM: ['=DSUM(A1:C10, "Sales", E1:F2)', '=DSUM(A1:C10, 3, E1:F2)'],
    DCOUNT: ['=DCOUNT(A1:C10, "Sales", E1:F2)'],
    DCOUNTA: ['=DCOUNTA(A1:C10, "Product", E1:F2)'],
    DAVERAGE: ['=DAVERAGE(A1:C10, "Sales", E1:F2)'],
    DMAX: ['=DMAX(A1:C10, "Sales", E1:F2)'],
    DMIN: ['=DMIN(A1:C10, "Sales", E1:F2)'],
    DGET: ['=DGET(A1:C10, "Product", E1:F2)'],
    DPRODUCT: ['=DPRODUCT(A1:C10, "Sales", E1:F2)'],
    DSTDEV: ['=DSTDEV(A1:C10, "Sales", E1:F2)'],
    DSTDEVP: ['=DSTDEVP(A1:C10, "Sales", E1:F2)'],
    DVAR: ['=DVAR(A1:C10, "Sales", E1:F2)'],
    DVARP: ['=DVARP(A1:C10, "Sales", E1:F2)']
};

/**
 * Generate a syntax string from function metadata
 */
function generateSyntax(name, parameters) {
    if (!parameters || parameters.length === 0) {
        return `=${name}()`;
    }
    
    const paramStrings = parameters.map((param, index) => {
        const optional = param.optionalArg || param.defaultValue !== undefined;
        const paramName = param.argumentType ? param.argumentType.toLowerCase() : `arg${index + 1}`;
        return optional ? `[${paramName}]` : paramName;
    });
    
    return `=${name}(${paramStrings.join(', ')})`;
}

/**
 * Get category for a function
 */
function getCategory(name) {
    return FUNCTION_CATEGORIES[name] || 'Other';
}

/**
 * Get example formulas for a function
 */
function getExamples(name) {
    return EXAMPLE_FORMULAS[name] || [`=${name}()`, `=${name}(...)`];
}

/**
 * Generate a description based on function name and parameters
 */
function generateDescription(name, parameters) {
    const descriptions = {
        // Logical
        IF: 'Returns one value if a condition is true, another if false',
        AND: 'Returns TRUE if all arguments are true',
        OR: 'Returns TRUE if any argument is true',
        NOT: 'Reverses the logical value of its argument',
        TRUE: 'Returns the logical value TRUE',
        FALSE: 'Returns the logical value FALSE',
        IFERROR: 'Returns a value you specify if a formula evaluates to an error; otherwise returns the result of the formula',
        IFNA: 'Returns the value you specify if the expression resolves to #N/A; otherwise returns the result of the expression',
        XOR: 'Returns a logical exclusive OR of all arguments',
        SWITCH: 'Evaluates an expression against a list of values and returns the corresponding result',
        
        // Math
        SUM: 'Adds all the numbers in a range of cells',
        SUMIF: 'Adds the cells specified by a given condition or criteria',
        SUMIFS: 'Adds the cells specified by a given set of conditions or criteria',
        SUMPRODUCT: 'Returns the sum of the products of corresponding ranges or arrays',
        PRODUCT: 'Multiplies all the numbers given as arguments',
        SUBTOTAL: 'Returns a subtotal in a list or database',
        AGGREGATE: 'Returns an aggregate in a list or database',
        POWER: 'Returns the result of a number raised to a power',
        SQRT: 'Returns the positive square root of a number',
        ABS: 'Returns the absolute value of a number',
        ROUND: 'Rounds a number to a specified number of digits',
        ROUNDDOWN: 'Rounds a number down, toward zero',
        ROUNDUP: 'Rounds a number up, away from zero',
        MROUND: 'Returns a number rounded to the desired multiple',
        CEILING: 'Rounds a number up to the nearest integer or to the nearest multiple of significance',
        CEILINGMATH: 'Rounds a number up to the nearest integer or to the nearest multiple of significance',
        FLOOR: 'Rounds a number down to the nearest integer or to the nearest multiple of significance',
        FLOORMATH: 'Rounds a number down to the nearest integer or to the nearest multiple of significance',
        INT: 'Rounds a number down to the nearest integer',
        TRUNC: 'Truncates a number to an integer by removing the fractional part',
        MOD: 'Returns the remainder from division',
        QUOTIENT: 'Returns the integer portion of a division',
        SIGN: 'Returns the sign of a number',
        GCD: 'Returns the greatest common divisor',
        LCM: 'Returns the least common multiple',
        COMBIN: 'Returns the number of combinations for a given number of items',
        FACT: 'Returns the factorial of a number',
        RAND: 'Returns a random number between 0 and 1',
        RANDBETWEEN: 'Returns a random integer between specified numbers',
        
        // Statistical
        AVERAGE: 'Returns the average of its arguments',
        AVERAGEA: 'Returns the average of its arguments, including numbers, text, and logical values',
        AVERAGEIF: 'Returns the average of cells that meet a single criteria',
        AVERAGEIFS: 'Returns the average of cells that meet multiple criteria',
        COUNT: 'Counts the number of cells that contain numbers',
        COUNTA: 'Counts the number of cells that are not empty',
        COUNTBLANK: 'Counts the number of empty cells in a range',
        COUNTIF: 'Counts the number of cells that meet a single criteria',
        COUNTIFS: 'Counts the number of cells that meet multiple criteria',
        MAX: 'Returns the maximum value in a list of arguments',
        MAXA: 'Returns the maximum value in a list of arguments, including text and logical values',
        MIN: 'Returns the minimum value in a list of arguments',
        MINA: 'Returns the minimum value in a list of arguments, including text and logical values',
        MEDIAN: 'Returns the median of the given numbers',
        MODE: 'Returns the most frequently occurring value in an array or range',
        STDEV: 'Estimates standard deviation based on a sample',
        STDEVP: 'Calculates standard deviation based on the entire population',
        VAR: 'Estimates variance based on a sample',
        VARP: 'Calculates variance based on the entire population',
        CORREL: 'Returns the correlation coefficient between two data sets',
        PEARSON: 'Returns the Pearson product moment correlation coefficient',
        PERCENTILE: 'Returns the k-th percentile of values in a range',
        QUARTILE: 'Returns the quartile of a data set',
        RANK: 'Returns the rank of a number in a list of numbers',
        LARGE: 'Returns the k-th largest value in a data set',
        SMALL: 'Returns the k-th smallest value in a data set',
        
        // Lookup & Reference
        VLOOKUP: 'Looks up a value in the first column of a table and returns a value in the same row from a specified column',
        HLOOKUP: 'Looks up a value in the top row of a table and returns a value in the same column from a specified row',
        INDEX: 'Returns a value or reference of the cell at the intersection of a particular row and column',
        MATCH: 'Returns the relative position of an item in an array that matches a specified value',
        XLOOKUP: 'Searches a range or array for a match and returns the corresponding item from a second range or array',
        XMATCH: 'Returns the relative position of an item in an array or range',
        CHOOSE: 'Chooses a value or action to perform from a list of values based on an index number',
        LOOKUP: 'Looks up a value in a one-row or one-column range or from an array',
        OFFSET: 'Returns a reference to a range that is a specified number of rows and columns from a cell or range of cells',
        INDIRECT: 'Returns the reference specified by a text string',
        ADDRESS: 'Returns a reference as text to a single cell in a worksheet',
        ROW: 'Returns the row number of a reference',
        ROWS: 'Returns the number of rows in a reference or array',
        COLUMN: 'Returns the column number of a reference',
        COLUMNS: 'Returns the number of columns in a reference or array',
        TRANSPOSE: 'Returns a vertical range of cells as a horizontal range, or vice versa',
        SORT: 'Sorts the contents of a range or array',
        UNIQUE: 'Returns a list of unique values in a range or array',
        FILTER: 'Filters a range of data based on supplied criteria',
        
        // Date & Time
        DATE: 'Returns the serial number of a particular date',
        TODAY: 'Returns the serial number of the current date',
        NOW: 'Returns the serial number of the current date and time',
        DAY: 'Returns the day of a date, as a number from 1 to 31',
        MONTH: 'Returns the month of a date, as a number from 1 to 12',
        YEAR: 'Returns the year of a date, as a four-digit number',
        HOUR: 'Returns the hour of a time value',
        MINUTE: 'Returns the minute of a time value',
        SECOND: 'Returns the second of a time value',
        TIME: 'Returns the serial number of a particular time',
        TIMEVALUE: 'Converts a time in the form of text to a serial number',
        DATEVALUE: 'Converts a date in the form of text to a serial number',
        DAYS: 'Returns the number of days between two dates',
        DAYS360: 'Calculates the number of days between two dates based on a 360-day year',
        EDATE: 'Returns the serial number of the date that is the indicated number of months before or after the start date',
        EOMONTH: 'Returns the serial number of the last day of the month before or after a specified number of months',
        NETWORKDAYS: 'Returns the number of whole workdays between two dates',
        NETWORKDAYSINTL: 'Returns the number of whole workdays between two dates using parameters to indicate weekend days',
        WORKDAY: 'Returns the serial number of the date before or after a specified number of workdays',
        WORKDAYINTL: 'Returns the serial number of the date before or after a specified number of workdays using parameters to indicate weekend days',
        WEEKNUM: 'Returns the week number in the year',
        ISOWEEKNUM: 'Returns the ISO week number in the year for a given date',
        WEEKDAY: 'Returns the day of the week corresponding to a date',
        YEARFRAC: 'Returns the year fraction representing the number of whole days between two dates',
        DATEDIF: 'Calculates the number of days, months, or years between two dates',
        
        // Text
        CONCATENATE: 'Joins several text strings into one text string',
        CONCAT: 'Combines the text from multiple ranges and/or strings',
        TEXTJOIN: 'Combines the text from multiple ranges and/or strings with a delimiter',
        LEFT: 'Returns the specified number of characters from the start of a text string',
        RIGHT: 'Returns the specified number of characters from the end of a text string',
        MID: 'Returns a specific number of characters from a text string starting at the position you specify',
        LEN: 'Returns the number of characters in a text string',
        TRIM: 'Removes all spaces from text except for single spaces between words',
        UPPER: 'Converts text to uppercase',
        LOWER: 'Converts text to lowercase',
        PROPER: 'Capitalizes the first letter in each word of a text value',
        FIND: 'Finds one text value within another (case-sensitive)',
        SEARCH: 'Finds one text value within another (not case-sensitive)',
        SUBSTITUTE: 'Substitutes new text for old text in a text string',
        REPLACE: 'Replaces part of a text string with a different text string',
        REPT: 'Repeats text a given number of times',
        TEXT: 'Formats a number and converts it to text',
        VALUE: 'Converts a text string that represents a number to a number',
        EXACT: 'Checks whether two text strings are identical',
        CHAR: 'Returns the character specified by the code number',
        CODE: 'Returns a numeric code for the first character in a text string',
        CLEAN: 'Removes all nonprintable characters from text',
        T: 'Checks whether a value is text and returns the text if it is, or returns double quotes (empty text) if it is not',
        
        // Financial
        FV: 'Returns the future value of an investment',
        PV: 'Returns the present value of an investment',
        PMT: 'Calculates the payment for a loan based on constant payments and a constant interest rate',
        PPMT: 'Returns the payment on the principal for an investment for a given period',
        IPMT: 'Returns the interest payment for an investment for a given period',
        NPER: 'Returns the number of periods for an investment',
        RATE: 'Returns the interest rate per period of an annuity',
        NPV: 'Returns the net present value of an investment based on a series of periodic cash flows and a discount rate',
        IRR: 'Returns the internal rate of return for a series of cash flows',
        XIRR: 'Returns the internal rate of return for a schedule of cash flows that is not necessarily periodic',
        XNPV: 'Returns the net present value for a schedule of cash flows that is not necessarily periodic',
        EFFECT: 'Returns the effective annual interest rate',
        NOMINAL: 'Returns the annual nominal interest rate',
        DB: 'Returns the depreciation of an asset for a specified period using the fixed-declining balance method',
        DDB: 'Returns the depreciation of an asset for a specified period using the double-declining balance method',
        SLN: 'Returns the straight-line depreciation of an asset for one period',
        SYD: 'Returns the sum-of-years digits depreciation of an asset for a specified period',
        CUMIPMT: 'Returns the cumulative interest paid between two periods',
        CUMPRINC: 'Returns the cumulative principal paid on a loan between two periods',
        RRI: 'Returns an equivalent interest rate for the growth of an investment',
        PDURATION: 'Returns the number of periods required by an investment to reach a specified value',
        FVSCHEDULE: 'Returns the future value of an initial principal after applying a series of compound interest rates',
        
        // Information
        ISBLANK: 'Returns TRUE if the value is blank',
        ISERR: 'Returns TRUE if the value is any error value except #N/A',
        ISERROR: 'Returns TRUE if the value is any error value',
        ISLOGICAL: 'Returns TRUE if the value is a logical value',
        ISNA: 'Returns TRUE if the value is the #N/A error value',
        ISNONTEXT: 'Returns TRUE if the value is not text',
        ISNUMBER: 'Returns TRUE if the value is a number',
        ISREF: 'Returns TRUE if the value is a reference',
        ISTEXT: 'Returns TRUE if the value is text',
        ISFORMULA: 'Returns TRUE if there is a reference to a cell that contains a formula',
        ISEVEN: 'Returns TRUE if the number is even',
        ISODD: 'Returns TRUE if the number is odd',
        N: 'Returns a value converted to a number',
        NA: 'Returns the error value #N/A',
        TYPE: 'Returns a number indicating the data type of a value',
        
        // Trigonometry
        SIN: 'Returns the sine of an angle',
        COS: 'Returns the cosine of an angle',
        TAN: 'Returns the tangent of an angle',
        ASIN: 'Returns the arcsine of a number',
        ACOS: 'Returns the arccosine of a number',
        ATAN: 'Returns the arctangent of a number',
        ATAN2: 'Returns the arctangent from x- and y-coordinates',
        SINH: 'Returns the hyperbolic sine of a number',
        COSH: 'Returns the hyperbolic cosine of a number',
        TANH: 'Returns the hyperbolic tangent of a number',
        ASINH: 'Returns the inverse hyperbolic sine of a number',
        ACOSH: 'Returns the inverse hyperbolic cosine of a number',
        ATANH: 'Returns the inverse hyperbolic tangent of a number',
        COT: 'Returns the cotangent of an angle',
        ACOT: 'Returns the arccotangent of a number',
        COTH: 'Returns the hyperbolic cotangent of a number',
        ACOTH: 'Returns the inverse hyperbolic cotangent of a number',
        SEC: 'Returns the secant of an angle',
        CSC: 'Returns the cosecant of an angle',
        SECH: 'Returns the hyperbolic secant of an angle',
        CSCH: 'Returns the hyperbolic cosecant of an angle',
        DEGREES: 'Converts radians to degrees',
        RADIANS: 'Converts degrees to radians',
        PI: 'Returns the value of pi',
        
        // Array
        ARRAYFORMULA: 'Enables the display of values returned from an array formula into multiple rows and/or columns',
        MMULT: 'Returns the matrix product of two arrays',
        MDETERM: 'Returns the matrix determinant of an array',
        MINVERSE: 'Returns the inverse matrix for the matrix stored in an array',
        MUNIT: 'Returns the unit matrix for the specified dimension',
        
        // Database
        DSUM: 'Adds the numbers in the field column of records in the database that match the conditions you specify',
        DCOUNT: 'Counts the cells that contain numbers in the field column of records in the database that match the conditions you specify',
        DCOUNTA: 'Counts nonblank cells in the field column of records in the database that match the conditions you specify',
        DAVERAGE: 'Returns the average of selected database entries',
        DMAX: 'Returns the maximum value from selected database entries',
        DMIN: 'Returns the minimum value from selected database entries',
        DGET: 'Extracts from a database a single record that matches the specified criteria',
        DPRODUCT: 'Multiplies the values in the field column of records in the database that match the conditions you specify',
        DSTDEV: 'Estimates the standard deviation based on a sample of selected database entries',
        DSTDEVP: 'Calculates the standard deviation based on the entire population of selected database entries',
        DVAR: 'Estimates variance based on a sample from selected database entries',
        DVARP: 'Calculates variance based on the entire population of selected database entries',
        
        // Engineering
        BIN2DEC: 'Converts a binary number to decimal',
        BIN2HEX: 'Converts a binary number to hexadecimal',
        BIN2OCT: 'Converts a binary number to octal',
        DEC2BIN: 'Converts a decimal number to binary',
        DEC2HEX: 'Converts a decimal number to hexadecimal',
        DEC2OCT: 'Converts a decimal number to octal',
        HEX2BIN: 'Converts a hexadecimal number to binary',
        HEX2DEC: 'Converts a hexadecimal number to decimal',
        HEX2OCT: 'Converts a hexadecimal number to octal',
        OCT2BIN: 'Converts an octal number to binary',
        OCT2DEC: 'Converts an octal number to decimal',
        OCT2HEX: 'Converts an octal number to hexadecimal',
        BITAND: 'Returns a bitwise AND of two numbers',
        BITOR: 'Returns a bitwise OR of two numbers',
        BITXOR: 'Returns a bitwise XOR of two numbers',
        BITLSHIFT: 'Returns a value number shifted left by shift_amount bits',
        BITRSHIFT: 'Returns a value number shifted right by shift_amount bits',
        DELTA: 'Tests whether two values are equal',
        GESTEP: 'Tests whether a number is greater than a threshold value',
        COMPLEX: 'Converts real and imaginary coefficients into a complex number',
        CONVERT: 'Converts a number from one measurement system to another',
        ERF: 'Returns the error function',
        ERFC: 'Returns the complementary error function',
        IMABS: 'Returns the absolute value (modulus) of a complex number',
        IMAGINARY: 'Returns the imaginary coefficient of a complex number',
        IMREAL: 'Returns the real coefficient of a complex number',
        IMARGUMENT: 'Returns the argument theta, an angle expressed in radians',
        IMCONJUGATE: 'Returns the complex conjugate of a complex number',
        IMCOS: 'Returns the cosine of a complex number',
        IMCOSH: 'Returns the hyperbolic cosine of a complex number',
        IMCOT: 'Returns the cotangent of a complex number',
        IMCSC: 'Returns the cosecant of a complex number',
        IMSEC: 'Returns the secant of a complex number',
        IMSECH: 'Returns the hyperbolic secant of a complex number',
        IMSIN: 'Returns the sine of a complex number',
        IMSINH: 'Returns the hyperbolic sine of a complex number',
        IMTAN: 'Returns the tangent of a complex number',
        IMTANH: 'Returns the hyperbolic tangent of a complex number',
        IMLN: 'Returns the natural logarithm of a complex number',
        IMLOG10: 'Returns the base-10 logarithm of a complex number',
        IMLOG2: 'Returns the base-2 logarithm of a complex number',
        IMEXP: 'Returns the exponential of a complex number',
        IMPOWER: 'Returns a complex number raised to an integer power',
        IMPRODUCT: 'Returns the product of 2 to 255 complex numbers',
        IMSUM: 'Returns the sum of two or more complex numbers',
        IMSUB: 'Returns the difference of two complex numbers',
        IMSQRT: 'Returns the square root of a complex number',
        IMDIV: 'Returns the quotient of two complex numbers',
        
        // Web
        ENCODEURL: 'Returns a URL-encoded string',
        WEBSERVICE: 'Returns data from a web service on the Internet or Intranet'
    };
    
    return descriptions[name] || `Performs ${name.toLowerCase()} operation`;
}

export default async function (fastify, opts) {
    fastify.get('', {
        schema: {
            tags: ['Metadata'],
            summary: 'List Available Formula Methods',
            description: 'Returns all built-in HyperFormula functions with descriptions, categories, syntax, and example formulas',
            response: {
                200: MethodsResponseSchema
            }
        }
    }, async (req, reply) => {
        try {
            // Build a temporary HyperFormula instance to get function information
            const hf = HyperFormula.buildEmpty({
                licenseKey: 'gpl-v3'
            });
            
            try {
                // Get all registered function names
                const functionNames = hf.getRegisteredFunctionNames();
                
                // Get function registry for metadata
                const functionRegistry = hf._functionRegistry;
                
                // Build method list with metadata
                const methods = functionNames.map(name => {
                    // Get function metadata if available
                    let metadata = null;
                    try {
                        metadata = functionRegistry.getMetadata(name);
                    } catch (e) {
                        // Some functions may not have metadata
                    }
                    
                    // Build parameters array
                    const parameters = [];
                    if (metadata && metadata.parameters) {
                        metadata.parameters.forEach((param, index) => {
                            parameters.push({
                                name: `arg${index + 1}`,
                                type: param.argumentType || 'ANY',
                                optional: param.optionalArg || false,
                                description: param.defaultValue !== undefined 
                                    ? `Optional, default: ${param.defaultValue}` 
                                    : undefined
                            });
                        });
                    }
                    
                    // Handle variable arguments
                    if (metadata && metadata.repeatLastArgs && parameters.length > 0) {
                        const lastParam = parameters[parameters.length - 1];
                        lastParam.name = `${lastParam.name}, ...`;
                    }
                    
                    return {
                        name: name,
                        category: getCategory(name),
                        description: generateDescription(name, metadata),
                        syntax: generateSyntax(name, metadata?.parameters),
                        parameters: parameters,
                        examples: getExamples(name),
                        isVolatile: metadata?.isVolatile || false
                    };
                });
                
                // Sort methods by category then by name
                methods.sort((a, b) => {
                    if (a.category !== b.category) {
                        return a.category.localeCompare(b.category);
                    }
                    return a.name.localeCompare(b.name);
                });
                
                // Get unique categories
                const categories = [...new Set(methods.map(m => m.category))].sort();
                
                return reply.send({
                    status: 'success',
                    methods: methods,
                    count: methods.length,
                    categories: categories
                });
            } finally {
                // Always destroy the HyperFormula instance
                hf.destroy();
            }
        } catch (error) {
            req.log.error(error);
            return reply.status(500).send({
                status: 'error',
                message: 'Failed to retrieve available methods'
            });
        }
    });
}
